#! /bin/sh
# ndb    This used to do various ndb operations.
# chkconfig: - 99 10
# description: NDB service script

### BEGIN INIT INFO
#Required start
#Required stop
#Required Restart
#Required status
### END INIT INFO

# EDIT THE BELOW LINES -START
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
NDB_PATH=/home/user/xnc
# END

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

DESC="Execution of NDB as a Service"
NAME=ndb
SCRIPTNAME=/etc/init.d/$NAME


do_start()
{
  $NDB_PATH/runxnc.sh -start
}

do_stop()
{
  $NDB_PATH/runxnc.sh -stop
}

do_status()
{
  $NDB_PATH/runxnc.sh -status
}

do_restart()
{
  do_stop

  do_start
}

#execute the statements depends on the input

case $1 in
   start)
      do_start
     ;;

   stop)
     do_stop
     ;;

   restart)
     do_restart
     ;;

   status)
      do_status
     ;;
   *)
      echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
      exit 1
      ;;
esac

:
