import sys
sys.path.append('pysdk')
from insieme.mit import access
access.rest()
directory = access.MoDirectory(ip='172.21.128.100', port='8000', user='admin', password='password')
polUni = directory.lookupByDn('uni')
fvTenant = directory.create('fv.Tenant', polUni, name='T2')
fvCtx = directory.create('fv.Ctx', fvTenant, name='T2')
fvBD = directory.create('fv.BD', fvTenant, name='BD1')
fvRsCtx = directory.create('fv.RsCtx', fvBD, tnFvCtxName='T2')
fvSubnet = directory.create('fv.Subnet', fvBD, ip='10.0.0.128/24', scope='private')
fvSubnet = directory.create('fv.Subnet', fvBD, ip='10.0.1.128/24', scope='public')
aaaDomainRef = directory.create('aaa.DomainRef', fvTenant, name='T2')
vzFilter = directory.create('vz.Filter', fvTenant, name='rmi')
vzEntry = directory.create('vz.Entry', vzFilter, etherT='ipv4', prot='6', dFromPort='1099', dToPort='1099', name='FilterEntry')
vzFilter = directory.create('vz.Filter', fvTenant, name='http')
vzEntry = directory.create('vz.Entry', vzFilter, etherT='ipv4', prot='6', dFromPort='80', dToPort='80', name='FilterEntry')
vzFilter = directory.create('vz.Filter', fvTenant, name='oracle')
vzEntry = directory.create('vz.Entry', vzFilter, etherT='ipv4', prot='6', dFromPort='1521', dToPort='1521', name='FilterEntry')
vzBrCP = directory.create('vz.BrCP', fvTenant, name='RMI')
vzSubj = directory.create('vz.Subj', vzBrCP, name='rmi')
vzRsSubjFiltAtt = directory.create('vz.RsSubjFiltAtt', vzSubj, tDn='uni/tn-T2/flt-rmi')
vzBrCP = directory.create('vz.BrCP', fvTenant, name='HTTP')
vzSubj = directory.create('vz.Subj', vzBrCP, name='http')
vzRsSubjFiltAtt = directory.create('vz.RsSubjFiltAtt', vzSubj, tDn='uni/tn-T2/flt-http')
vzBrCP = directory.create('vz.BrCP', fvTenant, name='ORACLE')
vzSubj = directory.create('vz.Subj', vzBrCP, name='oracle')
vzRsSubjFiltAtt = directory.create('vz.RsSubjFiltAtt', vzSubj, tDn='uni/tn-T2/flt-oracle')
fvAp = directory.create('fv.Ap', fvTenant, name='www.T2.com')
fvAEPg = directory.create('fv.AEPg', fvAp, name='APP')
fvRsBd = directory.create('fv.RsBd', fvAEPg, tnFvBDName='BD1')
fvRsCons = directory.create('fv.RsCons', fvAEPg, tDn='uni/tn-T2/brc-ORACLE')
fvRsProv = directory.create('fv.RsProv', fvAEPg, tDn='uni/tn-T2/brc-RMI')
fvAEPg = directory.create('fv.AEPg', fvAp, name='WEB')
fvRsBd = directory.create('fv.RsBd', fvAEPg, tnFvBDName='BD1')
fvRsCons = directory.create('fv.RsCons', fvAEPg, tDn='uni/tn-T2/brc-RMI')
fvRsProv = directory.create('fv.RsProv', fvAEPg, tDn='uni/tn-T2/brc-HTTP')
fvAEPg = directory.create('fv.AEPg', fvAp, name='DB')
fvRsBd = directory.create('fv.RsBd', fvAEPg, tnFvBDName='BD1')
fvSubnet = directory.create('fv.Subnet', fvAEPg, ip='100.1.3.1/24')
fvRsProv = directory.create('fv.RsProv', fvAEPg, tDn='uni/tn-T2/brc-ORACLE')
l3extOut = directory.create('l3ext.Out', fvTenant, name='Outside')
l3extInstP = directory.create('l3ext.InstP', l3extOut, name='Outside')
l3extSubnet = directory.create('l3ext.Subnet', l3extInstP, ip='0.0.0.0')
fvRsCons = directory.create('fv.RsCons', l3extInstP, tDn='uni/tn-T2/brc-HTTP')
l3extLNodeP = directory.create('l3ext.LNodeP', l3extOut, name='node18')
l3extRsNodeL3OutAtt = directory.create('l3ext.RsNodeL3OutAtt', l3extLNodeP, tDn='topology/pod-1/node-18', rtrId='1.2.3.4')
bgpPeerP = directory.create('bgp.PeerP', l3extLNodeP, addr='10.10.10.10')
l3extLIfP = directory.create('l3ext.LIfP', l3extLNodeP, name='port18')
l3extRsPathL3OutAtt = directory.create('l3ext.RsPathL3OutAtt', l3extLIfP, ifInstT='l3-port', addr='1.2.3.4', tDn='topology/pod-1/paths-18/pathep-[eth1/31]')
bgpExtP = directory.create('bgp.ExtP', l3extOut)
l3extRsEctx = directory.create('l3ext.RsEctx', l3extOut, tnFvCtxName='T2')
bgpCtxPol = directory.create('bgp.CtxPol', fvTenant, name='bgpCtxPolicy')
bgpPeerPfxPol = directory.create('bgp.PeerPfxPol', fvTenant, name='bgpPeerPolicy')
d = directory.commit(fvTenant)
