#! /bin/sh
### BEGIN INIT INFO
# Provides:          NDB
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: Run the NDB application as a service
# Description:       NDB as a service by providing the path of XNC/ and JAVA_HOME
### END INIT INFO

# EDIT THE BELOW LINES -START
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
NDB_PATH=/home/user/xnc
# END

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

DESC="Execution of NDB as a Service"
NAME=ndb
SCRIPTNAME=/etc/init.d/$NAME


do_start()
{
  $NDB_PATH/runxnc.sh -start
}

do_stop()
{
  $NDB_PATH/runxnc.sh -stop
}

do_status()
{
  $NDB_PATH/runxnc.sh -status
}

do_restart()
{
  do_stop

  do_start
}

#execute the statements depends on the input

case $1 in
   start)
      do_start
     ;;

   stop)
     do_stop
     ;;

   restart)
     do_restart
     ;;

   status)
      do_status
     ;;
   *)
      echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
      exit 1
      ;;
esac

:
